### ISSUE TITLE
Support for ipv6 dynamic dns?

### ISSUE THREAD

**Issue by chmac** [linickx/rsdns#25]
Firstly, thanks for releasing an awesome package. It makes rackspace's DNS super easy to work with.

Secondly, is there support for ipv6 dynamic dns? I had a look at the `rsdns-dc.sh` code and it seems to be very much hard coded to ipv6. But I do see that there's ipv6 support in the package, so maybe the dynamic dns part is hiding somewhere I haven't found?

You open to helping if I work towards a pull request? My bash fu is not very strong, but I know the basics, and I'd be happy to jump in and give it a go.

If you're wondering about the reasoning, my ISP very helpfully changes my ipv6 subnet on a semi regular basis! I can probably tell from my `ifconfig` output what my IP is, I'm hoping my router is smart enough to match the TTLs, I assume it is. But a web facing use of icanhazip.com would also be fine.

**Comment by linickx** [comment]
Hi, Thanks for the effort :+1: 

Adding IPv6 to the dynamic DNS client has been on the todo list since c4c3bd3daa316876ccbc1123ca268b0003b0764c , but since my ISP doesn't support a native ipv6 connection it's just been a low priority... I'll have a look through what you have done and see what I can merge/borrow/steal. :wink:
