### ISSUE TITLE
Error: record for host.domainname.com not found

### ISSUE THREAD

**Issue by SPDurkee** [linickx/rsdns#37]
I am unable to update any a records with rsdns dc as I receive a "record for host.domainname.com not found" error.

Upon further investigation it appears the record ID's and record names are in the wrong order per the  get_recordid fuction.

Changing lines:
iNAME=`echo $i  | awk -F "|" '{print $2}'`
iRECORDID=`echo $i  | awk -F "|" '{print $1}'
corrects this issue.
I swaped $1 and $2.

**Comment by linickx** [comment]
Hi, I've just [re-run the unit tests](https://travis-ci.org/linickx/rsdns/builds/170716008) and yep even though the build completes it does look like it's broken since the [last release build](https://travis-ci.org/linickx/rsdns/builds/170716035) - there's a bunch of "not found" in the log.

Can you send me a pull request to run travis against?

**Comment by linickx** [comment]
Should be fixed by 32c822f1d962795c4ba347a54fa73906f5a7f549
